services:
- docker
before_script:
- export SAVE=$PWD cnt="ubuprxctr" slim=".slim"
script:
- "./slimmer.sh"
before_deploy:
- cd
- wget `curl -s https://api.github.com/repos/appc/docker2aci/releases | grep browser_download_url
  | head -n 1 | cut -d '"' -f 4` -O d2a.tar.gz
- tar -zxf d2a.tar.gz && rm d2a.tar.gz && d2a=`ls | grep "docker2aci*"` && d2a=`basename  $d2a`
  && alias d2a='${PWD}/${d2a}/docker2aci'
- docker save -o ${cnt}${slim}.tar ${cnt}${slim}
- "${PWD}/${d2a}/docker2aci ${cnt}${slim}.tar"
- xz -9 -c ${cnt}${slim}.tar > ${cnt}${slim}.tar.xz
- docker login -e $QUAYE -u $QUAYL -p $QUAYP quay.io
- docker tag ${cnt}${slim} quay.io/natostanco/$cnt:$TRAVIS_TAG
- docker push quay.io/natostanco/$cnt:$TRAVIS_TAG
deploy:
  provider: releases
  file:
  - ${cnt}${slim}.tar.xz 
  - ${cnt}${slim}-latest.aci 
  skip_cleanup: true
  on:
    tags: true
